# Generated by Django 2.2.5 on 2021-08-12 09:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('year', models.DateField(default=datetime.date(1950, 1, 1))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Owner')),
            ],
        ),
    ]
